Check JSON formatting of data in ConfigMap
Signed-off-by: Radim Hrazdil <rhrazdil@redhat.com>

diff --git a/bridge-filtering b/bridge-filtering
--- a/bridge-filtering
+++ b/bridge-filtering
@@ -116,6 +116,9 @@ create_rules_for_filtering() {
     local filtering_chain="${CNI_IFNAME}-${direction}"
     local policy_filtering_chain="${CNI_IFNAME}-${config_id}-${direction}"
 
+    # check JSON is well-formatted and can be parsed with jq
+    echo "$config" | jq &> /dev/null || exitWithError "${CNI_VERSION}" "Failed to parse JSON config, check formatting"
+    
     _create_policy_filtering_chain() {
         local config_id="$1"
         local config="$2"
